version: "3.8"

services:
  dns_server:
    image: jpillora/dnsmasq
    container_name: dns-server
    restart: always
    ports:
      - "192.168.75.131:53:53/udp"
      - "192.168.75.131:53:53/tcp"
    volumes:
      - ./dns-server/dnsmasq.conf:/etc/dnsmasq.conf

  servidor_dhcp:
    build: ./dhcp-server
    container_name: servidor_dhcp
    cap_add:
      - NET_ADMIN
    networks:
      red_estudio:
        ipv4_address: 192.168.30.2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    restart: unless-stopped
    volumes:
      - ./web-data/index.html:/usr/share/nginx/html/index.html:ro
    networks: # <-- AGREGAR ESTO PARA CONECTARLO A LA RED INTERNA
      - red_estudio

  ftp_server:
    image: fauria/vsftpd
    container_name: ftp-server
    restart: always
    ports:
      - "2121:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=root
      - FTP_PASS=1234
      - PASV_ADDRESS=192.168.75.131
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110

  pc1_cliente:
    build: ./ubuntu-client
    container_name: pc1
    depends_on:
      - servidor_dhcp
    cap_add:
      - NET_ADMIN
    networks:
      - red_estudio

  pc2_cliente:
    build: ./ubuntu-client
    container_name: pc2
    depends_on:
      - servidor_dhcp
    cap_add:
      - NET_ADMIN
    networks:
      - red_estudio

  pc01_ssh:
    image: ubuntu:latest
    container_name: pc01
    command: sleep infinity
    ports:
      - "2222:22"

  pc02_ssh:
    image: ubuntu:latest
    container_name: pc02
    command: sleep infinity
    ports:
      - "2223:22"

networks:
  red_estudio:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24 # <-- CAMBIO DE SUBRED
          gateway: 192.168.100.1 # <-- CAMBIO DE GATEWAY
