services:
  dns_server:
    image: jpillora/dnsmasq
    container_name: dns-server
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - TZ=America/Mexico_City
    volumes:
      - ./dns-server/dnsmasq.conf:/etc/dnsmasq.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  servidor_dhcp:
    build: ./dhcp-server
    container_name: servidor_dhcp
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Mexico_City
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      red_estudio:
        ipv4_address: 192.168.100.2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - red_estudio
    environment:
      - TZ=America/Mexico_City # Define la zona horaria de Querétaro
    volumes:
      - ./web-data:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro # Sincroniza el reloj del host con el contenedor
      - /etc/timezone:/etc/timezone:ro # Sincroniza la definición de la zona

  oracle_11g:
    build:
      context: ./oracle_11g
      target: dev
    ports:
      - "1521:1521"
    shm_size: "1gb"
    restart: always
    networks:
      - red_estudio # <--- Cambia redes_net por red_estudio

  ftp_server:
    image: fauria/vsftpd
    container_name: ftp-server
    restart: always
    ports:
      - "2121:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=root
      - FTP_PASS=1234
      - PASV_ADDRESS=192.168.75.131
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - TZ=America/Mexico_City
    volumes:
      - ./web-data:/home/vsftpd/root # <-- NUEVO: El FTP escribe en la misma carpeta web
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  pc1_cliente:
    build: ./ubuntu-client
    container_name: pc1
    depends_on:
      - servidor_dhcp
    cap_add:
      - NET_ADMIN
    networks:
      - red_estudio

  pc2_cliente:
    build: ./ubuntu-client
    container_name: pc2
    depends_on:
      - servidor_dhcp
    cap_add:
      - NET_ADMIN
    networks:
      - red_estudio

  pc01_ssh:
    image: ubuntu:latest
    container_name: pc01
    command: sleep infinity
    ports:
      - "2222:22"

  pc02_ssh:
    image: ubuntu:latest
    container_name: pc02
    command: sleep infinity
    ports:
      - "2223:22"

networks:
  red_estudio:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24 # <-- CAMBIO DE SUBRED
          gateway: 192.168.100.1 # <-- CAMBIO DE GATEWAY
