server {
    listen       80;
    server_name  localhost;

    location / {
        # Política de Acceso Remoto:
        allow 127.0.0.1;
        #allow 192.168.75.1;  # Permitir tu Windows físico
        allow 192.168.75.128;  # Permitir tu Ubuntu virtual
        allow 192.168.100.0/24; # Permitir tráfico interno de Docker
        deny  all;           # Bloquear a todos los demás

        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}